### ISSUE TITLE
Index initialization Issue

### ISSUE THREAD

**Issue by akiselka-flexcon** [kontent-ai/integration-example-algolia#13]
### Brief bug description

Running the index initialization give me "Missing or invalid body, please check the documentation" and the index doesn't get created. 

### Repro steps

In postman I attempt to run the index initialization and pass it the required parameters. The only response I get is "Missing or invalid body, please check the documentation", No errors Netlify. 

### Expected behavior

What is the correct behavior?

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Additional context

I worked with Kontent.ai support and we couldn't get it resolved. 

### Screenshots

Add links to screenshots, if possible.

**Comment by JiriLojda** [comment]
Hi, thank you for reporting the issue. it seems the settings mentioned in the readme are not synchronized with the latest changes in the code. I've created a PR that synchronizes them together with some renaming of the configuration properties. https://github.com/kontent-ai/integration-example-algolia/pull/14 Would you mind checking that the body you send matches the `Config` type in the init function? To make sure the problem is, indeed, a wrong configuration in the request body. You can find the expected configuration (in the current version, before we merge the PR) here. https://github.com/kontent-ai/integration-example-algolia/blob/dd93e95839747487da256c623e748d841807fc88/src/functions/algolia-init-function.ts#L64-L70

**Comment by akiselka-flexcon** [comment]
That did the trick. Thanks!
