### ISSUE TITLE
Error message is not descriptive

### ISSUE THREAD

**Issue by pritisolanki** [kontent-ai/integration-example-algolia#7]
### Motivation

Why is this feature required? What problems does it solve?

Error message: "Some environment variables are missing. Please check the documentation" is not informative to developers. When the error is displayed in the webhook dashboard, they find it challenging to look for resources to help themselves.

### Proposed solution

Better error message. Like what exactly is missing would help.

Suggestions:
Environment variables are missing. Please add kontent secret and algolia API key.

### Additional context
None

**Comment by Nickm615** [comment]
I'd like to add something I found, if you don't include any env variables at all (or forget to deploy your site after adding them) you get the "Some environment variables are missing. Please check the documentation" error. However if you do have the appropriate environment variables but their values are wrong, you get "{"errorType":"object","errorMessage":"[object Object]","trace":[]}" which is even less helpful.

**Comment by JiriLojda** [comment]
Hi @pritisolanki, thank you for submitting your feedback. I created a PR (https://github.com/kontent-ai/integration-example-algolia/pull/9) that should include missing environment variables in the error message returned. Since it is a template to be customised, I tried keeping the code open to adding additional environment variables in the future so the resulting error message is a bit more general than your suggestion, but it should point out the missing variables clearly enough. We will merge the PR once it is properly reviewed.

**Comment by JiriLojda** [comment]
Hi @Nickm615, your issue is slightly different from this issue although it also relates to error messages. The problem is the way Netlify serializes uncaught exceptions in the code. There is no way we can verify that you provided the correct environment variables (at least for authorization keys) until we try to use them against the corresponding service which throws an error. Since it is simple enough, I created a PR (https://github.com/kontent-ai/integration-example-algolia/pull/8) that wraps the Netlify function handlers in a function that catches uncaught errors and serializes them with `JSON.stringify`. That makes the error readable in the response. Hopefully, this will simplify your development.
Btw. you can inspect those errors properly serialized in Netlify logs. Here is the official documentation. https://docs.netlify.com/functions/logs/
